### ISSUE TITLE
Debian patches to uses system libpng, libjpeg and libz

### ISSUE THREAD

**Issue by marillat** [OpenShot/libopenshot-audio#30]
Hi,
Could you include theses 3 patches from Debian to uses (if installed) system libraries ?
One year old patches.

Patches needed  
https://salsa.debian.org/multimedia-team/libopenshot-audio/blob/master/debian/patches/Use-the-system-libraries.patch
https://salsa.debian.org/multimedia-team/libopenshot-audio/blob/master/debian/patches/Fix-build-with-libpng16.patch
https://salsa.debian.org/multimedia-team/libopenshot-audio/blob/master/debian/patches/Use-non-prefixed-zlib-types.patch

**Comment by ferdnyc** [comment]
Closing this, as
1. We now use the system ZLIB in all builds
1. Since the set of JUCE modules we build was pruned for the JUCE 5 upgrade, the PNG and JPEG libs are no longer used at all (either bundled or system)
