### ISSUE TITLE
Possible overlinkage

### ISSUE THREAD

**Issue by ghisvail** [OpenShot/libopenshot-audio#4]
As reported by the Debian toolchain:

```
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libopenshot-audio3/usr/lib/x86_64-linux-gnu/libopenshot-audio.so.0.1.2 was not linked against libXinerama.so.1 (it uses none of the library's symbols)
```

Could you confirm whether this is accurate or a false positive.

**Comment by ferdnyc** [comment]
This can be closed as it's obsoleted by the JUCE 5 changes, which no longer depend on Xinerama. (Or any of the other X11 libs, once `CMakeLists.txt` is fixed.)
