### ISSUE TITLE
build problem on FreeBSD amd64

### ISSUE THREAD

**Issue by mustafejen** [OpenShot/libopenshot-audio#49]
Hello!

When trying to compile, I get:

per@konjak:~/tmp/test/videoeditors/libopenshot-audio/build$ make
Scanning dependencies of target openshot-audio
[ 11%] Building CXX object CMakeFiles/openshot-audio.dir/JuceLibraryCode/include_juce_audio_basics.cpp.o
In file included from /home/per/tmp/test/videoeditors/libopenshot-audio/JuceLibraryCode/include_juce_audio_basics.cpp:9:
In file included from /home/per/tmp/test/videoeditors/libopenshot-audio/JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.cpp:32:
In file included from /home/per/tmp/test/videoeditors/libopenshot-audio/JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.h:52:
In file included from /home/per/tmp/test/videoeditors/libopenshot-audio/JuceLibraryCode/modules/juce_core/juce_core.h:282:
/home/per/tmp/test/videoeditors/libopenshot-audio/JuceLibraryCode/modules/juce_core/containers/juce_HashMap.h:49:109: error: cast from pointer to smaller type 'juce::pointer_sized_uint'
      (aka 'unsigned int') loses information
    static int generateHash (const void* key, int upperLimit) noexcept      { return generateHash ((uint64) (pointer_sized_uint) key, upperLimit); }
                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /home/per/tmp/test/videoeditors/libopenshot-audio/build
*** Error code 1

Stop.
make[1]: stopped in /home/per/tmp/test/videoeditors/libopenshot-audio/build
*** Error code 1

Stop.
make: stopped in /home/per/tmp/test/videoeditors/libopenshot-audio/build

**Comment by ferdnyc** [comment]
@mustafejen Looks like the JUCE library doesn't support FreeBSD, see falkTX/Carla#503. The solution they took with Carla was to effectively replace most of JUCE with code that includes FreeBSD support (falkTX/Carla#523), I'm not sure if that's a realistic option for libopenshot-audio. (And in the end, there were still audio problems with Carla on FreeBSD, according to that second issue.)

**Comment by ferdnyc** [comment]
Closing as unsupported, unfortunately JUCE (and therefore libopenshot-audio) does not currently support FreeBSD.
