### ISSUE TITLE
Unused embedded dependencies?

### ISSUE THREAD

**Issue by ghisvail** [OpenShot/libopenshot-audio#5]
`libopenshot-audio` currently ships a stripped down copy of Juce which itself contains embedded copies of system libraries such as `pnglib`, `jpeglib` or `zlib`.

However, the embedded copies of `flac` and `vorbis` do not seem to be used anywhere, do they? I managed to build the library successfully with these dependencies stripped out and without specifying any additional build flags.

Could you confirm?

**Comment by jonoomph** [comment]
You are correct, I am not using the audio decoding source in JUCE. These are now ripped out. =)

**Comment by ghisvail** [comment]
Ping @jonoomph for version `0.1.3`?
