### ISSUE TITLE
Audo Ducking

### ISSUE THREAD

**Issue by zefram-cochrane** [OpenShot/libopenshot-audio#57]
Just moved to linux from macos and searching for an equivalent to ScreenFlow. OpenShot is closest but misses automated ducking. Which means a background track - music usually - gets its volume reduces when other tracks - VO usually - grow louder.

Screenflow makes trivially easy. Unless I misunderstand, I don't think Openshot has it ... and it's really, really, really useful. As it is I'm going to need to bring the audio into audacity and back again ... not a nice workflow!

**Comment by ferdnyc** [comment]
@zefram-cochrane 

Huh! That is _really_ odd — just a week before you posted this here, a completely different issue was opened at OpenShot/openshot-qt#2813 asking the exact same thing. I even had to go and double-check just now, to confirm that they weren't posted by the same user.

I'll copy my response to that issue:

I believe at least _similar_ functionality can be achieved in OpenShot, by setting your clips' Volume Mixing property to "Reduce". (The other options are "None" — the default — and "Average".)

If you do give that a try, please let us know whether it's sufficiently equivalent to the requested functionality, or what's lacking that makes it an inadequate substitute.

**Comment by RafaelLinux** [comment]
https://github.com/OpenShot/openshot-qt/issues/2813#issuecomment-517071451
